trigger:
  branches:
    include:
      - main
  tags:
    include: ['*']
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: gh-releases
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    publishExtension: ${{ parameters.publishExtension }}
    createGitHubRelease: true
    createGitHubReleaseChangelog: true
    buildSteps:
      - script: npm install
        displayName: Install dependencies

      - script: npm run vscode:prepublish
        displayName: Compile
